### ISSUE TITLE
运行项目报 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Vension** [guofudong/KotlinAndroid#1]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.gfd.video, PID: 22314
                  java.lang.NoClassDefFoundError: dagger.internal.Preconditions
                      at com.gfd.common.injection.component.DaggerAppComponent$Builder.appMoudle(DaggerAppComponent.java:48)
                      at com.gfd.common.common.BaseApplication.initInjection(BaseApplication.kt:30)
                      at com.gfd.common.common.BaseApplication.onCreate(BaseApplication.kt:23)
                      at com.gfd.video.MainApplication.onCreate(MainApplication.kt:16)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4632)
                      at android.app.ActivityThread.access$1800(ActivityThread.java:141)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5333)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by guofudong** [comment]
更新一下。

**Comment by guofudong** [comment]
更新一下。
